version: '3.3'

services:
  web:
        build: .
        command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
        expose:
          - 8000
        restart: always
        volumes:
          - static:/static
        env_file:
          - ./.env
        depends_on:
          - db
#        entrypoint: ./entrypoint.sh

#
  db:
          image: postgres
          container_name: postgres
          restart: always
          volumes:
            - postgres_data:/var/lib/postgresql/data/
          env_file:
            - ./.env


  nginx:
    build: ./nginx
    volumes:
      - ./static:/static
    ports:
      - "1337:80"
    depends_on:
      - web





volumes:
  static:
  postgres_data: